---
dist: trusty
language: python
python: "2.7"
# Use the new container infrastructure
sudo: required

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook -c local tests/test.yml -i tests/inventory --syntax-check
  # Actually install
  - ansible-playbook -c local tests/test.yml -i tests/inventory
  # experimental: list packages
  - dpkg -l
  - apt-cache policy nodejs
  - dpkg -L nodejs
  # experimental: test version
  - node --version || true
  - npm --version || true
  - which npm

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
